### ISSUE TITLE
convolution layer의 kernel weight 이미지를 텐서보드에서 찾을 수 없음

### ISSUE THREAD

**Issue by kuc2477** [dalgu90/splitnet-wrn#2]
![no-kernel-weight-images](https://user-images.githubusercontent.com/9589618/30973129-4f53049c-a4a7-11e7-879c-2f140b38b2df.png)

## 맥락
- 해당 모델의 pytorch 구현체를 작성했습니다. 
- 그러나 convolution layer의 kernel이 충분히 block diagonal하게 regularize되지 않습니다.
- 정상적인 구현체에선 kernel weight이 어떤 모습을 띄는지 비교하기 위해 본 저장소의 모델을 실행했습니다.

## 문제 및 상황
- convolution layer들의 kernel weight 이미지를 텐서보드에서 찾을 수 없습니다.
- `train.img_to_summary` 함수가 `split_[pqr]\d+` 텐서들에 대해서는 정상적으로 작동합니다.
- `train.img_to_summary` 함수가 왜 convolution layer들의 kernel에 대해서만 정상적으로 작동하지 않는지 의문입니다.

## 시스템 및 버전 정보
- OS: Ubuntu
- Python: 2.7
- tensorflow: 1.3.0
- tensorboard: 0.1.7
- numpy: 1.13.2
- matplotlib: 2.0.2

## 추가정보
- 학습을 위해 실행한 명령어는 다음과 같습니다: `./group.sh` (수정사항: `--group_summary_interval=150`)
- 텐서보드를 실행한 명령어는 다음과 같습니다: `tensorboard --logdir=./group_2-2-2`

**Comment by dalgu90** [comment]
Thank you for the issue, Junsoo!

Actually, there seems to have a problem in the `train.py` script and I guess it results from some changes in tensorflow. I found that when the name of an image summary conflicts with other names(variable or name scope), we cannot see it in tensorboard.

I will update the related code. But if you want to see the images of split conv kernels in tensorboard now, change the summary names(in `train.py`) like below.

Change this
```
img_summaries.append(img_to_summary(unit_3_0_shortcut_img, 'unit_3_0/shortcut'))
```
to this
```
img_summaries.append(img_to_summary(unit_3_0_shortcut_img, 'unit_3_0/ANOTHER_NAME'))
```

**Comment by dalgu90** [comment]
Fixed in c7718b5

**Comment by kuc2477** [comment]
빠르게 피드백 주셔서 감사합니다. 

추가적으로, 현재 작성중인 [pytorch 구현체](https://github.com/kuc2477/dl-papers/tree/master/Model-Optimization/splitnet/pytorch)에 논문의 모델 구조 그래픽 이미지를 가져다 사용해도 괜찮을지 궁금합니다.

**Comment by dalgu90** [comment]
Yes, you can use any of the graphics on the paper. Please mention the source correctly.

I just visited [your repo](https://github.com/kuc2477/dl-papers) and it's quite impressive. I hope you do well and make the repo richer.
